defaultDepartmentName: sages
development: true
server:
  port: 8000
spring:
  messages:
    basename: exceptions
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/departments
  jpa:
    hibernate:
      ddl-auto: create-drop
